---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: fts
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: FTS
    email: infrastructure@example.com
  parent: 
  children: []
  members: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: flex
spec:
  type: team
  parent: fts
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: karthikjayaraman80
spec:
  memberOf: [flex, guests]
